### ISSUE TITLE
Shirase's border is red, not blue

### ISSUE THREAD

**Issue by Prism019** [2Tie/TGMsim#15]
In TGMsim, the border for Shirase is blue. In TGM3, the border is red.

**Comment by 2Tie** [comment]
I did this to differentiate the two modes, so this is intentional. However, if you think it'd be better if both were red, i can change this.

**Comment by Prism019** [comment]
What? Here:

TGM3 Master - Blue
TGM3 Shirase - Red
TGMsim TGM3 Master - Grey (White?)
TGMsim TGM3 Shirase - Blue

See the problem?

**Comment by 2Tie** [comment]
Grey is Master (any game), Red is Death, Blue is Shirase, Pink is Konoha, and Green is Rounds iirc

was done so you can tell at a glance what mode is being played, though i'm open to suggestions

**Comment by 2Tie** [comment]
since the game and mode are visible in the top left of the screen, i've decided to "fix" all the mode colours.

**Comment by 2Tie** [comment]
should be reflected in the main branch now.
