### ISSUE TITLE
IRS will save you from dying

### ISSUE THREAD

**Issue by Prism019** [2Tie/TGMsim#18]
IRS will bump the piece up in TGM3 if the piece would kill you if it spawned normally.

**Comment by 2Tie** [comment]
up? as in floorkick? does this happen with all pieces or only I's and T's?

**Comment by 2Tie** [comment]
should be fixed.

**Comment by Prism019** [comment]
Right now, IRS can kill you if you rotate into block out. It should fail to rotate instead.

**Comment by 2Tie** [comment]
fixed (finally) in latest push.
