### ISSUE TITLE
Sounds ignore the Windows Mixer

### ISSUE THREAD

**Issue by Prism019** [2Tie/TGMsim#19]
When you start the game or change the mode (main menu/mode select/game/title screen etc.) the sound will go back to 100%, even when the Windows Mixer is set to 1%...

**Comment by 2Tie** [comment]
the audio levels now obey the preferences file as of today's push. it's editable in the preferences menu, but needs more work so it doesn't crash the game. edit the preferences file for now, it's the byte that says 55.

**Comment by 2Tie** [comment]
need to make this play nice with the volume mixer still

**Comment by 2Tie** [comment]
it should play nice with the mixer now - volumes aren't adjustable anymore, though. will continue to look into this.
