### ISSUE TITLE
Shirase regrets absent

### ISSUE THREAD

**Issue by 2Tie** [2Tie/TGMsim#26]
Shirase currently doesn't test for regrets.

**Comment by makiki99** [comment]
uh, does Shirase even has regrets?

**Comment by 2Tie** [comment]
it has Regrets for each section, but they don't alter the grade as i mentioned above. editing OP to reflect this.

**Comment by Prism019** [comment]
Actually, Shirase only has the Hole Regret. I mentioned this to you earlier, but I feel this went in one ear and out the other. Talk to me on discord.

**Comment by 2Tie** [comment]
section regrets added as of the latest dev push, though i'm not sure if you can even get them with ARS
