### ISSUE TITLE
BUG: Bloxeed piece generator innacurrate.

### ISSUE THREAD

**Issue by zaphod77** [2Tie/TGMsim#45]
Explanation.

1) Bloxeed doesn't loop at 1000
2) Bloxeed runs the main randomizer once to provide a seed to the piece generator (main randomizer is from Sega Tetris, but uses a default seed 1 higher)
3) Bloxeed ands the result from the piece generator with 0x7f, not 0x3f.
4) before doing a modulo 7, it checks the three high bits of the ANDed result (looks for a 7 there)
5) if found, set s/z conversion flag, otherwise clear it.
6) after doing modulo 7, if conversion flag is set, replace 1 and 2 with 0 (transform S and Z to I).
7) the main randomizer is used to choose items. it is advanced ce per piece, and a lookup table based on the lower 6 bits of the result and the height of the center 4 columns of the stack is used to determine items.

https://tetris.wiki/Bloxeed#Power_Blocks 

info on how to get powerups working.

**Comment by 2Tie** [comment]
item generation was already implemented a couple years ago, when i wrote the relevant section on that tetris.wiki page:
https://github.com/2Tie/TGMsim/blob/master/TGMsim/Modes/SegaBlox.cs
fixing up the generator's next on my todo list, since that seems rather quick and easy.
