### ISSUE TITLE
Piece Generator Konoha Mode Slow Down Potential

### ISSUE THREAD

**Issue by odiefrom** [2Tie/TGMsim#9]
The piece generator when in konoha mode can select an unusable piece randomly from the set of all tets, not just those for konoha mode.  While unlikely, this can cause slow down/stutters as the game has to keep hunting for a "correct" piece, potentially hitting unusable pieces enough time to make the frame's processing time longer than a single frame.

Solution: have the piece generator select from a modified selection of pieces that only include the usable pieces.

**Comment by 2Tie** [comment]
implemented the change suggested.
